DROP TABLE IF EXISTS RECORD;


CREATE TABLE RECORD
	(
	ID INTEGER NOT NULL AUTO_INCREMENT ,
	NAME VARCHAR(40)  NOT NULL ,
	SCORE INTEGER ,
	DEGREE INTEGER ,
	TIEMPO INTEGER ,
	PRIMARY KEY(ID)  
	);


INSERT INTO RECORD ( NAME, SCORE, DEGREE, TIEMPO ) VALUES ( 'MANU', 30, 4, 300 );

